language: java
notifications:
  slack:
    secure: TmQ3mFQrr4rUzhZfbJSqXGdeiX5lmpJ+1nlpAE+TOq4Miehn7AAICFdzuaLXlyk2FEpCvQ+Zl6iNdAn0Fdo0QzLkKPbJoM25mI3fmGs2daLEmVQjkEI5jVvzSBZwAnEPV6KeivG0IylIZQYoUaLAXAsaO93lc/I8d8qg/xNM0EE=
deploy:
  provider: releases
  api_key:
    secure: S2uJMgLaP5mYwc2v6NaEmN+o0rLJfEqrzpyfLEleL3tTTeK2Qgst47tch1/fi/S7pSelkKCORWdomqnAbjmje4VtzNuHioYOm2CoWp4xKosblyhvdpQT4JL7Itt3F0u++b2keMgWFgcuiCKPkM0f6qrkp+lmi2XPJctJ21ybzHQ=
  file: build/libs/xld-puppet-plugin-1.0.3.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-puppet-plugin
